### ISSUE TITLE
Can we custom a onClick method on D3 for dynamic charts?

### ISSUE THREAD

**Issue by wuxianliang** [Olical/d3-react#3]
Dear @Olical 
Controlling chart by props looks like Redux way. So I wonder that we can custom a onClick method for D3 or toReact() just like onClick in ordinary React's component.

``` javascript
Chart = React.createClass({
  changeData(){
    store.dispatch(Actions.changeData());// Redux' jobs
  }
  render(){
    chart.onClick(this.changeData)
    return chart.toReact()
  }
})
```

**Comment by Olical** [comment]
Sure, that should work. Although you can get React events right now with
`.prop('onClick', function () { return someFunction })`.

Sadly you can't just set it to a function, because the prop function
executes it's argument if it's a function so it can pass it data and an
index.

**Comment by Olical** [comment]
Sure, that should work. Although you can get React events right now with `.prop('onClick', function () { return someFunction })`.

Sadly you can't just set it to a function, because the prop function executes it's argument if it's a function so it can pass it data and an index.

**Comment by Olical** [comment]
I'm going to close this for now since you can just use `.prop('onClick', ...)`. You could add this custom function if you really wanted the cleaner API though.

``` javascript
d3.selection.prototype.onClick = function (fn) {
  this.prop('onClick', function () {
    return fn
  })
}
```

I hope this helps, feel free to open another issue or PR if you wish to add more things though. I'll be happy to discuss which direction this project should go in. I would like to keep it simple with a minimal API ideally.

I'd love to see what you end up building with this if you do eventually use it :+1:

**Comment by wuxianliang** [comment]
Thank you very much. I am reinstalling OS X. Will be back soon.
