### ISSUE TITLE
Why no state

### ISSUE THREAD

**Issue by niahoo** [Olical/d3-react#5]
Hi, 

I would like to know why you say "no state, as it should be". It seems that for every render you re-create a div. Why not create this div during initialisation and then use create/update pattern ?

Thank you

**Comment by Olical** [comment]
I didn't notice this issue, I don't think I received an email for some reason.

I believe things like [Reagent](https://reagent-project.github.io/) (a ClojureScript wrapper around React) and React itself have the right idea when they encourage you to build your UI using a series of [pure functions](https://en.wikipedia.org/wiki/Pure_function) (or as close as you can get to pure). This makes refactoring and reading code far easier because it's easier to reason about.

You can make assumptions like: Given an input of X, I will always get an output of Y. As soon as you introduce state or use or [free variables](https://en.wikipedia.org/wiki/Free_variables_and_bound_variables) you make it harder to make those assumptions.

So, "no state, as it should be" implies that rendering our UI from scratch each time (which is how React works) is a better solution in general. So this allows you to use D3 in that way, rendering anew each time instead of having to mutate something and _hopefully_ end up with the desired result.

When mutable state is involved (the DOM D3 mutates for example) you have **far** less confidence in the predictability of your code. If your component is a pure function you can move it anywhere and it will still work. If you have state, it probably won't.

I hope this explains my reasoning.

**Comment by niahoo** [comment]
Hi, thank you !

So you follow the react pattern as much as possible, which is great. I was looking for somme support for D3 nice animations, do you think it is achievable with this pattern ?

**Comment by Olical** [comment]
From my initial investigations, [react-motion](https://github.com/chenglou/react-motion) seems like a good approach. You can find more about it in [this issue](https://github.com/Olical/react-faux-dom/issues/2).

From [my recent post](http://oli.me.uk/2015/09/09/d3-within-react-the-right-way/) though I've replaced this approach (d3-react) with my other library [react-faux-dom](https://github.com/Olical/react-faux-dom). It gives you the same result (D3 without state) but much more efficiently and allows you to use all D3 methods.

I'm going to close this now but feel free to ask more questions if you want. I'd highly recommend checking out react-faux-dom if you want to use D3 within React though, this library can be seen as an early variation of it.

**Comment by niahoo** [comment]
Excellent, thanks !
